---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "jhseo-dev"
name:        "jhseo"
description: "Welcome to jhseo's dev-log. Enjoy your time."
url:         "http://jhseo99.github.io"
baseurl:     ""
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  sand:      '#D5C6A8'
  khaki:     '#B3D3B3'
  grey:      '#CCCBC2'
  sky:       '#B2D7E7'
  mint:      '#A8DFD2'
  
kramdown:
  auto_ids:  false

